### ISSUE TITLE
请问知道怎么处理多模块的项目吗

### ISSUE THREAD

**Issue by conleywa** [demo-pool/proguard-spring-boot-demo#1]
请问知道怎么处理多模块的项目吗
需要把子模块代码也进行混淆

**Comment by lxbzmy** [comment]
各个module都配置上

**Comment by conleywa** [comment]
那比如说A依赖了B模块，都配置上之后，package最外层的maven项目吗，A依赖的B模块的代码会改成混淆后的吗

**Comment by lxbzmy** [comment]
如果多模块最终只有一个app要发布，那么在最终的pom中配置proguard，然后需要额外设置include exclude。 看新的例子 : 5d6fd1e31c1295152d81ac9f2ab85ba604c87de9

如果多模块，每个模块各自发布，那么proguard各自独立。
